version: 0.2

phases:
  install:
    commands:
      - npm install
  build:
    commands:
      - npm run-script build
      - cd build && zip -q -r ../frontend-distribution . *
artifacts:
  files:
    - "frontend-distribution.zip"
